### PR TITLE
Update all.json

### PR DESCRIPTION
**Pull request by Yenthe-Bruynseels**
removed typo

### CODE REVIEW

**Comment by Yenthe-Bruynseels** [comment]
I saw a typo in the frontend, so I corrected it, so you guys could merge it if you want to, :)

**Comment by cskiwi** [comment]
recheck

**Comment by cskiwi** [comment]
Hey @Yenthe-Bruynseels thanks for the PR, can you accept the CLA before continuing?

**Comment by Yenthe-Bruynseels** [comment]
ik heb de Contributor Licentie Overeenkomst gelezen en verklaar mij hiermee akkoord

**Comment by cskiwi** [comment]
recheck

**Pull request merged**
